### ISSUE TITLE
Send strikes

### ISSUE THREAD

**Issue by authaldo** [SoPra-Team-17/Server#143]
TODO:
- [ ] Strike bei fehlender Aktion in Wahlphase: #114, #150
- [x] Strike bei fehlender Aktion im Game: #147 
- [x] Kick bei zu vielen Strikes: #149

<details><summary>Standardauschnitte zur Wahlphase</summary>

> Sollte P1 noch in der Wahlphase die Verbindung verloren haben, so
> wird die RequestItemChoiceMessage wiederholt (sofern die Letzte noch nicht richtig abgeschlossen
> wurde) oder, sofern möglich, die Nächste gesendet. War P1 bereits in der Ausrüstungsphase, so wird
> die RequestEquipmentChoiceMessage erneut gesendet.
> Doch wie erhält P1 nach dem Wiedereintritt seine bisherigen Wahlen? Hierfür wird die Request-
> MetaInformationMessage verwendet – die auch von Zuschauern hierfür verwendet werden kann.
> Der Spieler erhält über den Schlüssel Faction.Player1 (oder .Player2 wenn Spieler 2) seine
> bisherigen Charaktere und über den Schlüssel Gadgets.Player1 oder .Player2 wenn Spieler 2)
> seine bisher gewählten Gadgets.

</details>
